routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('period', 'PeriodController');
    Route::post('period/upload/{id}', 'PeriodController@upload')->name('upload');
    Route::get('period/reset/{id}', 'PeriodController@reset')->name('reset');
    Route::get('provision/report/{id}', 'PeriodController@report')->name('report');
    Route::get('provision/report/export/{id}', 'PeriodController@export')->name('export');

    Route::get('insurance', 'InsuranceController@index')->name('insurance.index');
    Route::delete('insurance/{id}', 'InsuranceController@delete')->name('insurance.delete');
    Route::post('insurance/get', 'InsuranceController@getInsurances')->name('insurance.get');
    Route::patch('insurance/update/{id}', 'InsuranceController@update')->name('insurance.update');
    Route::post('insurance/store', 'InsuranceController@store')->name('insurance.store');
    Route::post('insurance/batch-import', 'InsuranceController@batchImport')->name('insurance.import');
    Route::get('insurance/get-companies', 'InsuranceController@getCompanies')->name('insurance.companies');
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @if($periods->count())
                    <div class="card">
                        <div class="card-header">
                            <a href="{{ route('period.create') }}" class="btn btn-sm btn-primary">New Provision</a>
                        </div>
                        <table class="table table-striped">
                            <tr>
                                <th>Name</th>
                                <th>Year</th>
                                <th>Quartar</th>
                                <th>Action</th>
                            </tr>

                            @forelse($periods as $period)
                                <tr>
                                    <td>{{ $period->name }}</td>
                                    <td>{{$period->year}}</td>
                                    <td>{{$period->quarter}}</td>
                                    <td>
                                        <a href="{{ route('period.show', $period->id) }}" class="btn btn-sm btn-primary">View</a>
                                        <a href="{{ route('period.edit', $period->id) }}"
                                           class="btn btn-sm btn-primary">Edit</a>
                                        <button
                                            onclick="event.preventDefault(); document.getElementById('form{{ $period->id }}').submit();"
                                            type="button" class="btn btn-danger btn-sm">Delete
                                        </button>
                                        <form id="form{{ $period->id }}" style="display: none"
                                              action="{{route('period.destroy',$period->id)}}"
                                              method="POST">
                                            @method('DELETE')
                                            @csrf
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4" class="text-center">No Record Found please add new</td>
                                </tr>
                            @endforelse
                        </table>

                    </div>
                @else
                    <div class="card">
                        <div class="card-body text-center">
                            <a href="{{ route('period.create') }}" class="btn btn-primary">
                                Make New Provision
                            </a>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection