routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Auth::routes();

Route::middleware('auth')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('period', 'PeriodController');
    Route::post('period/upload/{id}', 'PeriodController@upload')->name('upload');
    Route::get('period/reset/{id}', 'PeriodController@reset')->name('reset');
    Route::get('provision/report/{id}', 'PeriodController@report')->name('report');
    Route::get('provision/report/export/{id}', 'PeriodController@export')->name('export');

    Route::get('insurance', 'InsuranceController@index')->name('insurance.index');
    Route::delete('insurance/{id}', 'InsuranceController@delete')->name('insurance.delete');
    Route::post('insurance/get', 'InsuranceController@getInsurances')->name('insurance.get');
    Route::patch('insurance/update/{id}', 'InsuranceController@update')->name('insurance.update');
    Route::post('insurance/store', 'InsuranceController@store')->name('insurance.store');
    Route::post('insurance/batch-import', 'InsuranceController@batchImport')->name('insurance.import');
    Route::get('insurance/get-companies', 'InsuranceController@getCompanies')->name('insurance.companies');
});

app/Period.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Period extends Model
{
    protected $fillable = ['name', 'year', 'quarter'];

    public function loans()
    {
        return $this->hasMany(Loan::class);
    }
}

app/Http/Controllers/PeriodController.php
<?php

namespace App\Http\Controllers;

use App\Exports\ReportAllExport;
use App\Imports\LoanImport;
use App\Loan;
use App\Period;
use App\Services\ReportServices;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Excel;

class PeriodController extends Controller
{
    /**
     * @var ReportServices
     */
    private $reportServices;

    /**
     * PeriodController constructor.
     * @param ReportServices $reportServices
     */
    public function __construct(ReportServices $reportServices)
    {
        $this->reportServices = $reportServices;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('periods.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $suffix = ['', 'st', 'nd', 'rd', 'th'];
        $request->validate([
            'year'    => 'required|numeric',
            'quarter' => 'required|numeric',
        ]);

        $user   = auth()->user();
        $period = $user->periods()->create([
            'name'    => $request->quarter.$suffix[$request->quarter].' quarter of '.$request->year,
            'year'    => $request->year,
            'quarter' => $request->quarter,
        ]);

        return redirect()->route('period.show', $period->id);
    }

    public function show($id)
    {
        $period = Period::with([
            'loans',
            'loans.acType',
        ])->findOrFail($id);


        return view('periods.show', compact('period'));
    }

    public function report($periodId)
    {
        $period  = Period::findOrFail($periodId);
        $master  = $this->reportServices->getReportData($periodId);
        $npaData = $this->reportServices->getNpa($periodId);

        return view('periods.reports', compact('master', 'period', 'npaData'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $period = Period::find($id);

        return view('periods.edit', compact('period'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int                      $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name'    => 'required',
            'year'    => 'required|numeric',
            'quarter' => 'required|numeric',
        ]);

        $quarter = Period::find($id);
        $quarter->update($request->only('name', 'year', 'quarter'));

        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Period::destroy($id);

        return redirect()->route('home');

    }

    public function upload(Request $request, $id)
    {
        Loan::where('period_id', $id)->delete();
        app(Excel::class)->import(new LoanImport($id), $request->file('file'), null, \Maatwebsite\Excel\Excel::XLSX);

        return redirect()->back();
    }

    public function reset($id)
    {
        Loan::where('period_id', $id)->delete();

        return redirect()->back();
    }

    public function export($periodId)
    {
        return app(Excel::class)->download(new ReportAllExport($periodId), 'report.xlsx');
    }
}

resources/views/periods/_report.blade.php
<table width="98%" border="1">
    <tr>
        <th>TYPES</th>
        @foreach(array_keys(reset($master)) as $header)
            <th>{{ strtoupper($header) }}</th>
        @endforeach
    </tr>
    @foreach($master as $key=>$row)
        <tr>
            <td>{{ strtoupper($key) }}</td>
            @foreach($row as $cell)
                <td>{{ strtoupper($cell) }}</td>
            @endforeach
        </tr>
    @endforeach
</table>

<table width="40%" border="1" style="margin-top: 15px">
    <tr>
        <th>PERFORMING</th>
        <td>{{ $npaData['performing'] }}</td>
    </tr>
    <tr>
        <th>NON-PERFORMING</th>
        <td>{{ $npaData['non-performing'] }}</td>
    </tr>
    <tr>
        <th>NPA</th>
        <td>{{ $npaData['npa'] }}</td>
    </tr>
</table>

resources/views/periods/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Create New Provision</div>
                    <div class="card-body">
                        <form method="POST" action="{{ route('period.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="year">Enter Year</label>
                                <select name="year" id="year" class="@error('year') is-invalid @enderror form-control">
                                    <option value="2077">2077</option>
                                    <option value="2078">2078</option>
                                    <option value="2079">2079</option>
                                    <option value="2080">2080</option>
                                </select>
                                @error('year')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="quarter">Enter Quarter</label>
                                <select name="quarter" id=""
                                        class="@error('quarter') is-invalid @enderror form-control">
                                    <option value="1">1st Quarter</option>
                                    <option value="2">2st Quarter</option>
                                    <option value="3">3st Quarter</option>
                                    <option value="4">4st Quarter</option>
                                </select>
                                @error('quarter')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary">Submit</button>
                                <a href="{{ route('home') }}" class="btn btn-danger" type="button">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/periods/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Update New Provision</div>
                    <div class="card-body">
                        <form method="post" action="{{ route('period.update', $period->id) }}"
                              enctype="multipart/form-data">
                            @method('patch')
                            @csrf
                            <div class="form-group">
                                <label for="name">Enter Title Of Provision</label>
                                <input type="text" class="@error('name') is-invalid @enderror form-control" id="name"
                                       placeholder="जस्तै: २०७७ पहिलो त्रैमास"
                                       name="name"
                                       value="{{ old('name', $period->name) }}"
                                >
                                @error('name')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="year">Enter Year</label>
                                <input type="text" class="@error('year') is-invalid @enderror form-control" id="name"
                                       placeholder="Enter Year"
                                       name="year"
                                       value="{{ old('year', $period->year) }}"
                                >
                                @error('year')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="quarter">Enter Quarter</label>
                                <select name="quarter"
                                        class="@error('quarter') is-invalid @enderror form-control">
                                    <option {{ old('quarter', $period->quarter) == 1 ? 'selected' : '' }} value="1">
                                        1st Quarter
                                    </option>
                                    <option {{ old('quarter', $period->quarter) == 2 ? 'selected' : '' }} value="2">2st
                                        Quarter
                                    </option>
                                    <option {{ old('quarter', $period->quarter) == 3 ? 'selected' : '' }} value="3">3st
                                        Quarter
                                    </option>
                                    <option {{ old('quarter', $period->quarter) == 4 ? 'selected' : '' }} value="4">4st
                                        Quarter
                                    </option>
                                </select>
                                @error('quarter')
                                <div class="invalid-feedback">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary">Submit</button>
                                <a href="{{ route('home') }}" class="btn btn-danger" type="button">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/periods/reports.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <table>
                <tr>
                    <td><h1 class="text-center">Rastriya Banijya Bank Ltd</h1></td>
                </tr>
                <tr>
                    <td>
                        <h3 class="text-center">{{ auth()->user()->name }}</h3>
                    </td>
                </tr>
                <tr>
                    <td>
                        <h4 class="text-center">{{ $period->name }}</h4>
                    </td>
                </tr>
            </table>
            @include('periods/_report', ['master'=>$master, 'npaData'=>$npaData])
        </div>
    </div>

@endsection

resources/views/periods/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-12">
                @if(!$period->loans->count())
                    <div class="card">
                        <div class="card-header">Upload Loan Os For {{ $period->name }}</div>
                        <div class="card-body">
                            <div class="row justify-content-center">
                                <form action="{{ route('upload', $period->id) }}" method="post"
                                      enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group">
                                        <label for="file" class="form-label">Please upload loan os file</label>
                                        <input type="file" name="file" accept=".xlsx"/>
                                        <button class="btn btn-sm btn-primary">Upload</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                @else
                    <div class="">
                        <div class="">
                            <div class="row">
                                <div class="col-md-6 d-flex align-items-center">
                                    <h2>Loan os of <b>{{ $period->name }}</b></h2>
                                </div>
                                <div class="col-md-6">
                                    <a href="{{ route('reset', $period->id) }}" class="btn btn-primary"
                                       style="float: right">
                                        <b-icon icon="arrow-clockwise"></b-icon>
                                        Reset & Upload again</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr/>
                    <provisions :id="{{ $period->id }}"></provisions>
                @endif
            </div>

        </div>
    </div>
@endsection